# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Administracion_Vivero.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Background = QtWidgets.QFrame(self.centralwidget)
        self.Background.setStyleSheet("QFrame{\n"
                                      "    background-color: rgb(236, 236, 236)\n"
                                      "}")
        self.Background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Background.setObjectName("Background")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Background)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Propietario_Frame = QtWidgets.QFrame(self.Background)
        self.Propietario_Frame.setEnabled(True)
        self.Propietario_Frame.setStyleSheet("QFrame{\n"
                                             "    border: 1.5px solid rgb(189, 189, 189);    \n"
                                             "    font-family: Arial, Helvetica, sans-serif;\n"
                                             "    font-size: 13px;\n"
                                             "    font-weight: 500;\n"
                                             "}\n"
                                             "\n"
                                             "#Datos_Propietario_Frame, #Datos_Finca_Frame{\n"
                                             "    background-color: rgb(220, 220, 220);\n"
                                             "    border: 0px;\n"
                                             "    border-radius: 5px;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton{\n"
                                             "    background-color: rgb(236, 236, 236);\n"
                                             "    color: rgb(95, 95, 95);\n"
                                             "    border: 1px solid rgb(182, 182, 182);\n"
                                             "    border-radius: 6px;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover{\n"
                                             "    background-color: rgb(85, 170, 255);\n"
                                             "    color: white;\n"
                                             "}")
        self.Propietario_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Propietario_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Propietario_Frame.setObjectName("Propietario_Frame")
        self.Finca_Frame = QtWidgets.QFrame(self.Propietario_Frame)
        self.Finca_Frame.setGeometry(QtCore.QRect(30, 308, 751, 241))
        self.Finca_Frame.setStyleSheet("")
        self.Finca_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Finca_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Finca_Frame.setObjectName("Finca_Frame")
        self.label_2 = QtWidgets.QLabel(self.Finca_Frame)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_2.setStyleSheet("border: 0px;\n"
                                   "background: transparent;\n"
                                   "margin-left: 1px;\n"
                                   "font-size: 2px;")
        self.label_2.setObjectName("label_2")
        self.Datos_Finca_Frame = QtWidgets.QFrame(self.Finca_Frame)
        self.Datos_Finca_Frame.setGeometry(QtCore.QRect(10, 50, 691, 161))
        self.Datos_Finca_Frame.setStyleSheet("")
        self.Datos_Finca_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Datos_Finca_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Datos_Finca_Frame.setObjectName("Datos_Finca_Frame")
        self.Agregar_Finca = QtWidgets.QPushButton(self.Datos_Finca_Frame)
        self.Agregar_Finca.setGeometry(QtCore.QRect(540, 120, 130, 23))
        self.Agregar_Finca.setObjectName("Agregar_Finca")
        self.Input_Frame_6 = QtWidgets.QFrame(self.Datos_Finca_Frame)
        self.Input_Frame_6.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.Input_Frame_6.setStyleSheet("QFrame{\n"
                                         "    border: 0px;\n"
                                         "    background: transparent\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit{\n"
                                         "    background-color: white;\n"
                                         "    border-radius: 0px;\n"
                                         "    font-size: 11px;\n"
                                         "    font-weight: 100;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "    border: 1.5px solid rgb(85, 170, 255);\n"
                                         "}")
        self.Input_Frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_Frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_Frame_6.setObjectName("Input_Frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Input_Frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.Input_Frame_6)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(self.Input_Frame_6)
        self.comboBox.setMouseTracking(False)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setStyleSheet("background: white;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.Input_Frame_7 = QtWidgets.QFrame(self.Datos_Finca_Frame)
        self.Input_Frame_7.setGeometry(QtCore.QRect(10, 70, 280, 41))
        self.Input_Frame_7.setStyleSheet("QFrame{\n"
                                         "    border: 0px;\n"
                                         "    background: transparent\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit{\n"
                                         "    background-color: white;\n"
                                         "    border-radius: 0px;\n"
                                         "    font-size: 11px;\n"
                                         "    font-weight: 100;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "    border: 1.5px solid rgb(85, 170, 255);\n"
                                         "}")
        self.Input_Frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_Frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_Frame_7.setObjectName("Input_Frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Input_Frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.Input_Frame_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.Municipio = QtWidgets.QTextEdit(self.Input_Frame_7)
        self.Municipio.setStyleSheet("")
        self.Municipio.setObjectName("Municipio")
        self.horizontalLayout_7.addWidget(self.Municipio)
        self.Input_Frame_8 = QtWidgets.QFrame(self.Datos_Finca_Frame)
        self.Input_Frame_8.setGeometry(QtCore.QRect(300, 20, 280, 41))
        self.Input_Frame_8.setStyleSheet("QFrame{\n"
                                         "    border: 0px;\n"
                                         "    background: transparent\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit{\n"
                                         "    background-color: white;\n"
                                         "    border-radius: 0px;\n"
                                         "    font-size: 11px;\n"
                                         "    font-weight: 100;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "    border: 1.5px solid rgb(85, 170, 255);\n"
                                         "}")
        self.Input_Frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_Frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_Frame_8.setObjectName("Input_Frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Input_Frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.Input_Frame_8)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.Registro_Castral = QtWidgets.QTextEdit(self.Input_Frame_8)
        self.Registro_Castral.setStyleSheet("")
        self.Registro_Castral.setObjectName("Registro_Castral")
        self.horizontalLayout_8.addWidget(self.Registro_Castral)
        self.Datos_Propietario_Frame = QtWidgets.QFrame(self.Propietario_Frame)
        self.Datos_Propietario_Frame.setGeometry(QtCore.QRect(20, 50, 701, 231))
        self.Datos_Propietario_Frame.setStyleSheet("")
        self.Datos_Propietario_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Datos_Propietario_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Datos_Propietario_Frame.setObjectName("Datos_Propietario_Frame")
        self.Agregar_Propietario = QtWidgets.QPushButton(self.Datos_Propietario_Frame)
        self.Agregar_Propietario.setGeometry(QtCore.QRect(550, 190, 130, 23))
        self.Agregar_Propietario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Agregar_Propietario.setStyleSheet("")
        self.Agregar_Propietario.setObjectName("Agregar_Propietario")
        self.Input_Frame = QtWidgets.QFrame(self.Datos_Propietario_Frame)
        self.Input_Frame.setGeometry(QtCore.QRect(10, 20, 321, 41))
        self.Input_Frame.setStyleSheet("QFrame{\n"
                                       "    border: 0px;\n"
                                       "    background: transparent;\n"
                                       "}\n"
                                       "\n"
                                       "QTextEdit{\n"
                                       "    background-color: white;\n"
                                       "    border-radius: 0px;\n"
                                       "    font-size: 11px;\n"
                                       "    font-weight: 100;\n"
                                       "}\n"
                                       "\n"
                                       "QTextEdit:focus{\n"
                                       "    border: 1.5px solid rgb(85, 170, 255);\n"
                                       "}")
        self.Input_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_Frame.setObjectName("Input_Frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Input_Frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.Input_Frame)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.User_Identification = QtWidgets.QTextEdit(self.Input_Frame)
        self.User_Identification.setStyleSheet("width: 40px")
        self.User_Identification.setObjectName("User_Identification")
        self.horizontalLayout.addWidget(self.User_Identification)
        self.Input_Frame_2 = QtWidgets.QFrame(self.Datos_Propietario_Frame)
        self.Input_Frame_2.setGeometry(QtCore.QRect(10, 70, 321, 41))
        self.Input_Frame_2.setStyleSheet("QFrame{\n"
                                         "    border: 0px;\n"
                                         "    background: transparent\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit{\n"
                                         "    background-color: white;\n"
                                         "    border-radius: 0px;\n"
                                         "    font-size: 11px;\n"
                                         "    font-weight: 100;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "    border: 1.5px solid rgb(85, 170, 255);\n"
                                         "}")
        self.Input_Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_Frame_2.setObjectName("Input_Frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Input_Frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.Input_Frame_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.User_Name = QtWidgets.QTextEdit(self.Input_Frame_2)
        self.User_Name.setStyleSheet("")
        self.User_Name.setObjectName("User_Name")
        self.horizontalLayout_2.addWidget(self.User_Name)
        self.Input_Frame_3 = QtWidgets.QFrame(self.Datos_Propietario_Frame)
        self.Input_Frame_3.setGeometry(QtCore.QRect(10, 120, 321, 41))
        self.Input_Frame_3.setStyleSheet("QFrame{\n"
                                         "    border: 0px;\n"
                                         "    background: transparent\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit{\n"
                                         "    background-color: white;\n"
                                         "    border-radius: 0px;\n"
                                         "    font-size: 11px;\n"
                                         "    font-weight: 100;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "    border: 1.5px solid rgb(85, 170, 255);\n"
                                         "}")
        self.Input_Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_Frame_3.setObjectName("Input_Frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Input_Frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.Input_Frame_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(154, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.User_Cel = QtWidgets.QTextEdit(self.Input_Frame_3)
        self.User_Cel.setStyleSheet("")
        self.User_Cel.setObjectName("User_Cel")
        self.horizontalLayout_3.addWidget(self.User_Cel)
        self.Input_Frame_4 = QtWidgets.QFrame(self.Datos_Propietario_Frame)
        self.Input_Frame_4.setGeometry(QtCore.QRect(340, 70, 248, 41))
        self.Input_Frame_4.setStyleSheet("QFrame{\n"
                                         "    border: 0px;\n"
                                         "    background: transparent\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit{\n"
                                         "    background-color: white;\n"
                                         "    border-radius: 0px;\n"
                                         "    font-size: 11px;\n"
                                         "    font-weight: 100;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "    border: 1.5px solid rgb(85, 170, 255);\n"
                                         "}")
        self.Input_Frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_Frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_Frame_4.setObjectName("Input_Frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Input_Frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.Input_Frame_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.User_Last_Name = QtWidgets.QTextEdit(self.Input_Frame_4)
        self.User_Last_Name.setStyleSheet("")
        self.User_Last_Name.setObjectName("User_Last_Name")
        self.horizontalLayout_4.addWidget(self.User_Last_Name)
        self.Input_Frame_5 = QtWidgets.QFrame(self.Datos_Propietario_Frame)
        self.Input_Frame_5.setGeometry(QtCore.QRect(340, 120, 248, 41))
        self.Input_Frame_5.setStyleSheet("QFrame{\n"
                                         "    border: 0px;\n"
                                         "    background: transparent\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit{\n"
                                         "    background-color: white;\n"
                                         "    border-radius: 0px;\n"
                                         "    font-size: 11px;\n"
                                         "    font-weight: 100;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "    border: 1.5px solid rgb(85, 170, 255);\n"
                                         "}")
        self.Input_Frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_Frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_Frame_5.setObjectName("Input_Frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Input_Frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.Input_Frame_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem4 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.User_Mail = QtWidgets.QTextEdit(self.Input_Frame_5)
        self.User_Mail.setStyleSheet("")
        self.User_Mail.setObjectName("User_Mail")
        self.horizontalLayout_5.addWidget(self.User_Mail)
        self.label = QtWidgets.QLabel(self.Propietario_Frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.label.setStyleSheet("border: 0px;\n"
                                 "background: transparent;\n"
                                 "margin-left: 1px;\n"
                                 "font-size: 2px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.Propietario_Frame)
        self.verticalLayout_2.addWidget(self.Background)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Agregar_Propietario.clicked.connect(self.add_owner)
        self.Agregar_Finca.clicked.connect(self.add_farm)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" "
                                        "font-size:8pt;\">Finca</span></p></body></html>"))
        self.Agregar_Finca.setText(_translate("MainWindow", "Agregar Finca"))
        self.label_8.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" "
                                        "font-size:8pt;\">Cultivo</span></p></body></html>"))
        self.comboBox.setCurrentIndex(-1)
        self.comboBox.setItemText(0, _translate("MainWindow", "Café"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Caña panelera"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Cítricos"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Fréjol"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Papa"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Papaya"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Plátano"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Yuca"))
        self.label_9.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" "
                                        "font-size:8pt;\">Municipio</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" font-size:8pt;\">Registro "
                                         "Castral</span></p></body></html>"))
        self.Agregar_Propietario.setText(_translate("MainWindow", "Agregar Propietario"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">Documento "
                                        "Identidad</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" "
                                        "font-size:8pt;\">Nombre</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" "
                                        "font-size:8pt;\">Tel/Cel</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" "
                                        "font-size:8pt;\">Apellido</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" "
                                        "font-size:8pt;\">Correo</span></p></body></html>"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" "
                                      "font-size:8pt;\">Propietario</span></p></body></html>"))

    def add_owner(self):
        identification = self.User_Identification.toPlainText().strip()
        name = self.User_Name.toPlainText().strip()
        last_name = self.User_Last_Name.toPlainText().strip()
        cellphone = self.User_Cel.toPlainText().strip()
        mail = self.User_Mail.toPlainText().strip()
        if identification and name and last_name and cellphone and mail:
            self.show_pop_up("Administracion Vivero", "Productor Agregado!!",
                             QtWidgets.QMessageBox.Information)
        else:
            self.show_pop_up("Administracion Vivero", "Error al insertar Productor",
                             QtWidgets.QMessageBox.Warning)

    def add_farm(self):
        crop = self.comboBox.currentText()
        municipality = self.Municipio.toPlainText().strip()
        cadastral_record = self.Registro_Castral.toPlainText().strip()
        if crop and municipality and cadastral_record:
            self.show_pop_up("Administracion Vivero", "Finca Agregada!!",
                             QtWidgets.QMessageBox.Information)
            self.Municipio.setText('')
            self.Registro_Castral.setText('')
        else:
            self.show_pop_up("Administracion Vivero", "Error al insertar Finca",
                             QtWidgets.QMessageBox.Warning)

    def show_pop_up(self, title, message, type_of_message):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(message)
        msg.setIcon(type_of_message)
        msg.setStandardButtons(QtWidgets.QMessageBox.Cancel | QtWidgets.QMessageBox.Ok)
        info = msg.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setWindowTitle("Administracion Vivero")
    MainWindow.show()
    sys.exit(app.exec_())
